ALTER TABLE "AacMessage" ADD COLUMN IF NOT EXISTS "source" TEXT NOT NULL DEFAULT 'aac';
ALTER TABLE "AacMessage" ADD COLUMN IF NOT EXISTS "senderPhone" TEXT;
ALTER TABLE "AacMessage" ADD COLUMN IF NOT EXISTS "externalId" TEXT;
